const CATALOG = [
    {
        id: 'el1',
        title: 'The Shining',
        img: 'img/catalog/TheShining.jpg',
        price: 483,
        autor:'Stephen King',
        genre: 'Horrors',
    },
    {
        id: 'el2',
        title: 'MR. Mercedes',
        img: 'img/catalog/MR.Mercedes.jpg',
        price: 507,
        autor:'Stephen King',
        genre: 'Detectives',
    },
    {
        id: 'el3',
        title: 'Fairy Tale',
        img: 'img/catalog/FairyTale.jpg',
        price: 592,
        autor:'Stephen King',
        genre: 'Fantasy',
    },
    {
        id: 'el4',
        title: '11/22/63',
        img: 'img/catalog/11-22-63.jpg',
        price: 580,
        autor:'Stephen King',
        genre: 'Fantasy',
    },
    {
        id: 'el5',
        title: 'The black obelisk',
        img: 'img/catalog/TheBlackObelisk.jpg',
        price: 338,
        autor:'Erich Maria Remarque',
        genre: 'Historic novels',
    },
    {
        id: 'el6',
        title: 'Spark of life',
        img: 'img/catalog/SparkOfLife.jpg',
        price: 338,
        autor:'Erich Maria Remarque',
        genre: 'Prose',
    },
    {
        id: 'el7',
        title: 'Heaven has no favorites',
        img: 'img/catalog/HeavenHasNoFavorites.jpg',
        price: 338,
        autor:'Erich Maria Remarque',
        genre: 'Prose',
    },
    {
        id: 'el8',
        title: 'Three Comrades',
        img: 'img/catalog/ThreeComrades.jpg',
        price: 338,
        autor:'Erich Maria Remarque',
        genre: 'Novel',
    },
    {
        id: 'el9',
        title: 'The Star Rover',
        img: 'img/catalog/TheStarRover.jpg',
        price: 168,
        autor:'Jack London',
        genre: 'Fantasy',
    },
    {
        id: 'el10',
        title: 'Martin Eden',
        img: 'img/catalog/MartinEden.jpg',
        price: 374,
        autor:'Jack London',
        genre: 'Prose',
    },

];